CREATE TABLE IF NOT EXISTS orders (
    order_id VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    type_order VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
